export const ALL_BADGES = [
  // LECTURE (10 badges)
  {
    id: 'newcomer',
    name: '🌱 Nouvelle Lectrice',
    description: 'Ajouter votre premier livre',
    requirement_type: 'book_count',
    requirement_value: 1,
    rarity: 'common',
    points: 10,
    category: 'reading',
    color_primary: '#90EE90',
    color_secondary: '#32CD32',
    icon: '🌱'
  },
  {
    id: 'bookworm',
    name: '📚 Rat de Bibliothèque',
    description: 'Lire 10 livres',
    requirement_type: 'book_count',
    requirement_value: 10,
    rarity: 'common',
    points: 25,
    category: 'reading',
    color_primary: '#FFB3D9',
    color_secondary: '#FF69B4',
    icon: '📚'
  },
  {
    id: 'avid_reader',
    name: '📖 Lectrice Assidue',
    description: 'Lire 25 livres',
    requirement_type: 'book_count',
    requirement_value: 25,
    rarity: 'rare',
    points: 50,
    category: 'reading',
    color_primary: '#87CEEB',
    color_secondary: '#4682B4',
    icon: '📖'
  },
  {
    id: 'book_devourer',
    name: '🔥 Dévoreuse de Livres',
    description: 'Lire 50 livres',
    requirement_type: 'book_count',
    requirement_value: 50,
    rarity: 'epic',
    points: 100,
    category: 'reading',
    color_primary: '#FF6347',
    color_secondary: '#DC143C',
    icon: '🔥'
  },
  {
    id: 'bibliophile',
    name: '👑 Bibliophile Légendaire',
    description: 'Lire 100 livres',
    requirement_type: 'book_count',
    requirement_value: 100,
    rarity: 'legendary',
    points: 250,
    category: 'reading',
    color_primary: '#FFD700',
    color_secondary: '#FFA500',
    icon: '👑'
  },
  {
    id: 'page_turner',
    name: '📄 Tourneuse de Pages',
    description: 'Lire 10 000 pages au total',
    requirement_type: 'total_pages',
    requirement_value: 10000,
    rarity: 'rare',
    points: 50,
    category: 'reading',
    color_primary: '#DDA0DD',
    color_secondary: '#9370DB',
    icon: '📄'
  },
  {
    id: 'marathon_reader',
    name: '🏃 Marathonienne',
    description: 'Lire 3 livres en une semaine',
    requirement_type: 'books_in_week',
    requirement_value: 3,
    rarity: 'epic',
    points: 75,
    category: 'reading',
    color_primary: '#FF4500',
    color_secondary: '#FF6347',
    icon: '🏃'
  },
  {
    id: 'night_owl',
    name: '🦉 Oiseau de Nuit',
    description: 'Terminer un livre après minuit',
    requirement_type: 'finish_after_midnight',
    requirement_value: 1,
    rarity: 'rare',
    points: 30,
    category: 'reading',
    color_primary: '#191970',
    color_secondary: '#000080',
    icon: '🦉',
    is_secret: true
  },
  {
    id: 'speed_reader',
    name: '⚡ Lectrice Éclair',
    description: 'Lire un livre de 300+ pages en moins de 24h',
    requirement_type: 'book_in_24h',
    requirement_value: 300,
    rarity: 'epic',
    points: 100,
    category: 'reading',
    color_primary: '#FFFF00',
    color_secondary: '#FFD700',
    icon: '⚡',
    is_secret: true
  },
  {
    id: 'year_goal_achieved',
    name: '🎯 Objectif Atteint',
    description: 'Atteindre votre objectif annuel',
    requirement_type: 'yearly_goal',
    requirement_value: 1,
    rarity: 'epic',
    points: 100,
    category: 'reading',
    color_primary: '#32CD32',
    color_secondary: '#228B22',
    icon: '🎯'
  },

  // DIVERSITÉ (5 badges)
  {
    id: 'explorer',
    name: '🗺️ Exploratrice',
    description: 'Lire 5 genres différents',
    requirement_type: 'genre_count',
    requirement_value: 5,
    rarity: 'common',
    points: 25,
    category: 'diversity',
    color_primary: '#FFB6C1',
    color_secondary: '#FF69B4',
    icon: '🗺️'
  },
  {
    id: 'genre_master',
    name: '🎭 Maîtresse des Genres',
    description: 'Lire 10 genres différents',
    requirement_type: 'genre_count',
    requirement_value: 10,
    rarity: 'rare',
    points: 50,
    category: 'diversity',
    color_primary: '#BA55D3',
    color_secondary: '#9370DB',
    icon: '🎭'
  },
  {
    id: 'globetrotter',
    name: '🌍 Globe-Trotteuse Littéraire',
    description: 'Lire des livres de 5 pays différents',
    requirement_type: 'country_count',
    requirement_value: 5,
    rarity: 'rare',
    points: 50,
    category: 'diversity',
    color_primary: '#20B2AA',
    color_secondary: '#008B8B',
    icon: '🌍'
  },
  {
    id: 'classic_lover',
    name: '📜 Amatrice de Classiques',
    description: 'Lire 5 livres publiés avant 1950',
    requirement_type: 'classic_books',
    requirement_value: 5,
    rarity: 'epic',
    points: 75,
    category: 'diversity',
    color_primary: '#8B4513',
    color_secondary: '#A0522D',
    icon: '📜'
  },
  {
    id: 'newbie_seeker',
    name: '✨ Découvreuse de Nouveautés',
    description: 'Lire 10 livres publiés cette année',
    requirement_type: 'new_releases',
    requirement_value: 10,
    rarity: 'rare',
    points: 40,
    category: 'diversity',
    color_primary: '#FFD700',
    color_secondary: '#FFA500',
    icon: '✨'
  },

  // SOCIAL (6 badges)
  {
    id: 'social_butterfly',
    name: '🦋 Papillon Social',
    description: 'Ajouter 5 amis',
    requirement_type: 'friend_count',
    requirement_value: 5,
    rarity: 'common',
    points: 20,
    category: 'social',
    color_primary: '#FF69B4',
    color_secondary: '#FFB6C1',
    icon: '🦋'
  },
  {
    id: 'connector',
    name: '🔗 Connecteuse',
    description: 'Ajouter 20 amis',
    requirement_type: 'friend_count',
    requirement_value: 20,
    rarity: 'rare',
    points: 50,
    category: 'social',
    color_primary: '#9370DB',
    color_secondary: '#BA55D3',
    icon: '🔗'
  },
  {
    id: 'reviewer',
    name: '✍️ Critique Littéraire',
    description: 'Écrire 10 avis de livres',
    requirement_type: 'review_count',
    requirement_value: 10,
    rarity: 'common',
    points: 30,
    category: 'social',
    color_primary: '#4682B4',
    color_secondary: '#5F9EA0',
    icon: '✍️'
  },
  {
    id: 'prolific_reviewer',
    name: '📝 Critique Prolifique',
    description: 'Écrire 50 avis de livres',
    requirement_type: 'review_count',
    requirement_value: 50,
    rarity: 'epic',
    points: 100,
    category: 'social',
    color_primary: '#1E90FF',
    color_secondary: '#4169E1',
    icon: '📝'
  },
  {
    id: 'club_member',
    name: '📖 Membre de Club',
    description: 'Rejoindre une lecture commune',
    requirement_type: 'shared_reading_join',
    requirement_value: 1,
    rarity: 'common',
    points: 20,
    category: 'social',
    color_primary: '#FF6347',
    color_secondary: '#FF7F50',
    icon: '📖'
  },
  {
    id: 'club_organizer',
    name: '👥 Organisatrice de Club',
    description: 'Créer 3 lectures communes',
    requirement_type: 'shared_reading_create',
    requirement_value: 3,
    rarity: 'rare',
    points: 60,
    category: 'social',
    color_primary: '#FF1493',
    color_secondary: '#FF69B4',
    icon: '👥'
  },

  // STREAK & RÉGULARITÉ (5 badges)
  {
    id: 'consistent',
    name: '🔥 Constante',
    description: 'Lire pendant 7 jours consécutifs',
    requirement_type: 'streak_days',
    requirement_value: 7,
    rarity: 'common',
    points: 25,
    category: 'streak',
    color_primary: '#FF4500',
    color_secondary: '#FF6347',
    icon: '🔥'
  },
  {
    id: 'dedicated',
    name: '💪 Dévouée',
    description: 'Lire pendant 30 jours consécutifs',
    requirement_type: 'streak_days',
    requirement_value: 30,
    rarity: 'rare',
    points: 75,
    category: 'streak',
    color_primary: '#FF8C00',
    color_secondary: '#FFA500',
    icon: '💪'
  },
  {
    id: 'unstoppable',
    name: '🚀 Inarrêtable',
    description: 'Lire pendant 100 jours consécutifs',
    requirement_type: 'streak_days',
    requirement_value: 100,
    rarity: 'epic',
    points: 150,
    category: 'streak',
    color_primary: '#DC143C',
    color_secondary: '#B22222',
    icon: '🚀'
  },
  {
    id: 'year_round',
    name: '📅 Toute l\'Année',
    description: 'Lire pendant 365 jours consécutifs',
    requirement_type: 'streak_days',
    requirement_value: 365,
    rarity: 'legendary',
    points: 500,
    category: 'streak',
    color_primary: '#FFD700',
    color_secondary: '#FF8C00',
    icon: '📅'
  },
  {
    id: 'monthly_achiever',
    name: '📆 Assidue Mensuelle',
    description: 'Terminer au moins 1 livre par mois pendant 6 mois',
    requirement_type: 'monthly_consistency',
    requirement_value: 6,
    rarity: 'rare',
    points: 60,
    category: 'streak',
    color_primary: '#9370DB',
    color_secondary: '#8A2BE2',
    icon: '📆'
  },

  // COMPLÉTION (4 badges)
  {
    id: 'series_completionist',
    name: '📚 Complétioniste de Séries',
    description: 'Terminer une série complète',
    requirement_type: 'series_complete',
    requirement_value: 1,
    rarity: 'rare',
    points: 50,
    category: 'completion',
    color_primary: '#4169E1',
    color_secondary: '#1E90FF',
    icon: '📚'
  },
  {
    id: 'bingo_master',
    name: '🎰 Maîtresse du Bingo',
    description: 'Compléter un bingo de lecture',
    requirement_type: 'bingo_complete',
    requirement_value: 1,
    rarity: 'epic',
    points: 100,
    category: 'completion',
    color_primary: '#FF1493',
    color_secondary: '#FF69B4',
    icon: '🎰'
  },
  {
    id: 'challenge_accepted',
    name: '🏆 Défi Accepté',
    description: 'Compléter 5 challenges différents',
    requirement_type: 'challenge_complete',
    requirement_value: 5,
    rarity: 'epic',
    points: 125,
    category: 'completion',
    color_primary: '#FFD700',
    color_secondary: '#FFA500',
    icon: '🏆'
  },
  {
    id: 'perfectionist',
    name: '💎 Perfectionniste',
    description: 'Noter 20 livres 5 étoiles',
    requirement_type: 'five_star_count',
    requirement_value: 20,
    rarity: 'rare',
    points: 50,
    category: 'completion',
    color_primary: '#87CEEB',
    color_secondary: '#4682B4',
    icon: '💎'
  }
];